/*
 * {elementName}
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swathi.assignment.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Status of the bulk upload.
 */
@ApiModel(description = "Status of the bulk upload.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-22T09:41:00.238+05:30")
public class BulkStatus {
  @JsonProperty("batchId")
  private BigDecimal batchId = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("numOfLeadsProcessed")
  private BigDecimal numOfLeadsProcessed = null;

  @JsonProperty("numOfRowsFailed")
  private BigDecimal numOfRowsFailed = null;

  @JsonProperty("numOfRowsWithWarning")
  private BigDecimal numOfRowsWithWarning = null;

  @JsonProperty("status")
  private String status = null;

  public BulkStatus batchId(BigDecimal batchId) {
    this.batchId = batchId;
    return this;
  }

   /**
   * Contact/Leads loaded
   * @return batchId
  **/
  @ApiModelProperty(value = "Contact/Leads loaded")
  public BigDecimal getBatchId() {
    return batchId;
  }

  public void setBatchId(BigDecimal batchId) {
    this.batchId = batchId;
  }

  public BulkStatus message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public BulkStatus numOfLeadsProcessed(BigDecimal numOfLeadsProcessed) {
    this.numOfLeadsProcessed = numOfLeadsProcessed;
    return this;
  }

   /**
   * Contact/Leads loaded
   * @return numOfLeadsProcessed
  **/
  @ApiModelProperty(value = "Contact/Leads loaded")
  public BigDecimal getNumOfLeadsProcessed() {
    return numOfLeadsProcessed;
  }

  public void setNumOfLeadsProcessed(BigDecimal numOfLeadsProcessed) {
    this.numOfLeadsProcessed = numOfLeadsProcessed;
  }

  public BulkStatus numOfRowsFailed(BigDecimal numOfRowsFailed) {
    this.numOfRowsFailed = numOfRowsFailed;
    return this;
  }

   /**
   * Failed count
   * @return numOfRowsFailed
  **/
  @ApiModelProperty(value = "Failed count")
  public BigDecimal getNumOfRowsFailed() {
    return numOfRowsFailed;
  }

  public void setNumOfRowsFailed(BigDecimal numOfRowsFailed) {
    this.numOfRowsFailed = numOfRowsFailed;
  }

  public BulkStatus numOfRowsWithWarning(BigDecimal numOfRowsWithWarning) {
    this.numOfRowsWithWarning = numOfRowsWithWarning;
    return this;
  }

   /**
   * Contact/Leads that had warnings
   * @return numOfRowsWithWarning
  **/
  @ApiModelProperty(value = "Contact/Leads that had warnings")
  public BigDecimal getNumOfRowsWithWarning() {
    return numOfRowsWithWarning;
  }

  public void setNumOfRowsWithWarning(BigDecimal numOfRowsWithWarning) {
    this.numOfRowsWithWarning = numOfRowsWithWarning;
  }

  public BulkStatus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the bulk job
   * @return status
  **/
  @ApiModelProperty(value = "Status of the bulk job")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkStatus bulkStatus = (BulkStatus) o;
    return Objects.equals(this.batchId, bulkStatus.batchId) &&
        Objects.equals(this.message, bulkStatus.message) &&
        Objects.equals(this.numOfLeadsProcessed, bulkStatus.numOfLeadsProcessed) &&
        Objects.equals(this.numOfRowsFailed, bulkStatus.numOfRowsFailed) &&
        Objects.equals(this.numOfRowsWithWarning, bulkStatus.numOfRowsWithWarning) &&
        Objects.equals(this.status, bulkStatus.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchId, message, numOfLeadsProcessed, numOfRowsFailed, numOfRowsWithWarning, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkStatus {\n");
    
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    numOfLeadsProcessed: ").append(toIndentedString(numOfLeadsProcessed)).append("\n");
    sb.append("    numOfRowsFailed: ").append(toIndentedString(numOfRowsFailed)).append("\n");
    sb.append("    numOfRowsWithWarning: ").append(toIndentedString(numOfRowsWithWarning)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

