/*
 * {elementName}
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: api-v2
 * Contact: support@cloud-elements.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swathi.assignment.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CloudLink
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-22T09:41:00.238+05:30")
public class CloudLink {
  @JsonProperty("cloudElementsLink")
  private String cloudElementsLink = null;

  @JsonProperty("expires")
  private String expires = null;

  @JsonProperty("providerLink")
  private String providerLink = null;

  @JsonProperty("providerViewLink")
  private String providerViewLink = null;

  public CloudLink cloudElementsLink(String cloudElementsLink) {
    this.cloudElementsLink = cloudElementsLink;
    return this;
  }

   /**
   * Get cloudElementsLink
   * @return cloudElementsLink
  **/
  @ApiModelProperty(value = "")
  public String getCloudElementsLink() {
    return cloudElementsLink;
  }

  public void setCloudElementsLink(String cloudElementsLink) {
    this.cloudElementsLink = cloudElementsLink;
  }

  public CloudLink expires(String expires) {
    this.expires = expires;
    return this;
  }

   /**
   * Get expires
   * @return expires
  **/
  @ApiModelProperty(value = "")
  public String getExpires() {
    return expires;
  }

  public void setExpires(String expires) {
    this.expires = expires;
  }

  public CloudLink providerLink(String providerLink) {
    this.providerLink = providerLink;
    return this;
  }

   /**
   * Get providerLink
   * @return providerLink
  **/
  @ApiModelProperty(value = "")
  public String getProviderLink() {
    return providerLink;
  }

  public void setProviderLink(String providerLink) {
    this.providerLink = providerLink;
  }

  public CloudLink providerViewLink(String providerViewLink) {
    this.providerViewLink = providerViewLink;
    return this;
  }

   /**
   * Get providerViewLink
   * @return providerViewLink
  **/
  @ApiModelProperty(value = "")
  public String getProviderViewLink() {
    return providerViewLink;
  }

  public void setProviderViewLink(String providerViewLink) {
    this.providerViewLink = providerViewLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudLink cloudLink = (CloudLink) o;
    return Objects.equals(this.cloudElementsLink, cloudLink.cloudElementsLink) &&
        Objects.equals(this.expires, cloudLink.expires) &&
        Objects.equals(this.providerLink, cloudLink.providerLink) &&
        Objects.equals(this.providerViewLink, cloudLink.providerViewLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloudElementsLink, expires, providerLink, providerViewLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudLink {\n");
    
    sb.append("    cloudElementsLink: ").append(toIndentedString(cloudElementsLink)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    providerLink: ").append(toIndentedString(providerLink)).append("\n");
    sb.append("    providerViewLink: ").append(toIndentedString(providerViewLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

